language: python

# run python
python:
 - "3.6"

sudo: required

# install dependencies
install:
 - pip install coveralls
 
# run tests
script:
 - coverage run --source=graph setup.py test
 #- coverage report
 
after_success:
 - coveralls
  
notifications:
 email: false
