language: python

# run python
python:
 - "3.6"

sudo: required
virtualenv:
 system_site_packages: true
 # install dependencies
install:
 - pip install coveralls
 - pip install -r requeriments
 
# run tests
script:
 - coverage run -m pytest src/test/test_core.py
 #- coverage run --source=src/graph setup.py test
 #- coverage report
 
after_success:
 - coveralls
  
notifications:
 email: false
